"""Render `RESULTS.md` from a snapshot.

Two sections carry the zoo's actual output, and the second one is the more
valuable of the two.

The **leaderboard** answers "what runs, and how fast". It carries `ms/epoch`
as a derived column, because on this part latency is epoch-bound rather than
MAC-bound below about a megabyte of weights, and that single ratio explains
most outliers at a glance. It carries the NPU-vs-M55 speedup for the same
reason: knowing where the accelerator actually wins is more interesting than
knowing that it usually does.

The **failure atlas** answers "what doesn't, and why" — grouped by normalised
error signature rather than by model, so the same underlying limitation hit by
six models reads as one constraint with a count of six rather than six
unrelated disappointments. Shrinking this table is the work.
"""

from __future__ import annotations

from pathlib import Path

from zoo.config import ROOT
from zoo.store.schema import Verdict
from zoo.store.snapshot import Snapshot

_VERDICT_MARK = {
    Verdict.DEPLOYED: "🟢 deployed",
    Verdict.MEASURED: "🟢 measured",
    Verdict.COMPILES: "🟡 compiles",
    Verdict.QUANTIZES: "🟡 quantizes",
    Verdict.IMPORTS: "🟠 imports",
    Verdict.SCREENED: "🟠 screened",
    Verdict.REJECTED: "🔴 rejected",
    Verdict.SKIPPED: "⚪ skipped",
    Verdict.UNTRIED: "⚪ untried",
}


def _pick(metrics: dict, *keys):
    """First present key among several spellings.

    Stages name the same quantity differently on purpose: the budget stage
    reports its own estimate (`peak_activation_fused`), while the compile stage
    reports what the compiler allocated (`activations_bytes`, straight out of
    `network_c_info.json`). The leaderboard shows whichever is the strongest
    evidence available, preferring measured over estimated.
    """
    for key in keys:
        value = metrics.get(key)
        if value not in (None, ""):
            return value
    return None


def _kb(value) -> str:
    if value in (None, ""):
        return "—"
    try:
        return f"{float(value) / 1024:,.0f}"
    except (TypeError, ValueError):
        return "—"


def _num(value, fmt: str = "{:.2f}") -> str:
    if value in (None, ""):
        return "—"
    try:
        return fmt.format(float(value))
    except (TypeError, ValueError):
        return "—"


def _epochs(metrics: dict) -> str:
    total = metrics.get("epochs_total")
    if total in (None, ""):
        return "—"
    hw = metrics.get("epochs_hw", 0)
    hy = metrics.get("epochs_hybrid", 0)
    sw = metrics.get("epochs_sw", 0)
    return f"{total} ({hw}H/{hy}y/{sw}S)"


def _ms_per_epoch(metrics: dict) -> str:
    latency = metrics.get("latency_ms_median")
    epochs = metrics.get("epochs_total")
    if not latency or not epochs:
        return "—"
    try:
        return f"{float(latency) / float(epochs):.3f}"
    except (TypeError, ValueError, ZeroDivisionError):
        return "—"


def _speedup(variants: dict) -> str:
    """NPU vs Cortex-M55, when both backends were measured for one graph."""
    npu = m55 = None
    for vid, state in variants.items():
        latency = state.metrics.get("latency_ms_median")
        if not latency:
            continue
        if vid.endswith("/npu"):
            npu = min(float(latency), npu) if npu else float(latency)
        elif vid.endswith("/m55"):
            m55 = min(float(latency), m55) if m55 else float(latency)
    if not npu or not m55:
        return "—"
    return f"{m55 / npu:.2f}×"


def render(snap: Snapshot, *, recipes: dict | None = None) -> str:
    recipes = recipes or {}
    rows = snap.rows()

    counts: dict[str, int] = {}
    for graph in rows:
        counts[graph.verdict] = counts.get(graph.verdict, 0) + 1

    lines: list[str] = [
        "# Results",
        "",
        "<!-- GENERATED by `zoo report`. Do not edit; edit the event log instead. -->",
        "",
        f"{len(rows)} graph(s) across {len({g.model_id for g in rows})} model(s) · "
        f"{snap.total_events} events"
        + (f" · {snap.infra_events} infra" if snap.infra_events else ""),
        "",
    ]

    if counts:
        parts = [
            f"{_VERDICT_MARK.get(v, v)} {n}"
            for v, n in sorted(counts.items(), key=lambda kv: -Verdict.rank(kv[0]))
        ]
        lines += ["  ·  ".join(parts), ""]

    lines += [
        "> Fidelity numbers marked ⚠ come from synthetic calibration and are not",
        "> meaningful as accuracy. Note also that ST's int8 realisation is not",
        "> bit-compatible with ONNX Runtime's QDQ semantics — a measured case showed",
        "> cosine 0.996 alongside a systematic +0.23 mean bias — so on-device scores",
        "> must be recalibrated against the deployed artifact, never the host one.",
        "",
        "## Leaderboard",
        "",
    ]

    header = (
        "| model | graph | task | verdict | weights KB | act KB | pool | epochs | "
        "ms | RTF | ms/epoch | NPU:M55 | int8 cos | profile | blocked at |"
    )
    lines += [header, "|" + "---|" * 15]

    for graph in rows:
        best = graph.best
        metrics = best.metrics if best else {}
        recipe = recipes.get(graph.model_id)
        task = getattr(recipe, "task", "") if recipe else ""
        profile = (best.variant_id.split("/")[0] if best and best.variant_id else "—")
        cos = metrics.get("ontarget_cos") or metrics.get("int8_cos")
        synthetic = bool(metrics.get("calibration_synthetic"))
        cos_cell = _num(cos, "{:.4f}") + (" ⚠" if synthetic and cos else "")
        lines.append(
            "| "
            + " | ".join(
                [
                    graph.model_id,
                    graph.graph_id,
                    task or "—",
                    _VERDICT_MARK.get(graph.verdict, graph.verdict),
                    # Compiler-reported first, analytic estimate as fallback.
                    _kb(_pick(metrics, "weights_bytes", "quantised_weight_bytes",
                              "weight_bytes")),
                    _kb(_pick(metrics, "activations_bytes", "peak_activation_fused")),
                    str(_pick(metrics, "pool_placement", "placement") or "—"),
                    _epochs(metrics),
                    _num(metrics.get("latency_ms_median")),
                    _num(metrics.get("rtf"), "{:.3f}"),
                    _ms_per_epoch(metrics),
                    _speedup(graph.variants),
                    cos_cell,
                    profile,
                    (best.blocked_by if best and best.blocked_by else "—"),
                ]
            )
            + " |"
        )

    # -- failure atlas ----------------------------------------------------

    lines += ["", "## Failure atlas", ""]
    if not snap.signatures:
        lines += ["_No failures recorded yet._", ""]
    else:
        lines += [
            "Grouped by normalised error signature, most frequent first. One row here",
            "is one real constraint, however many models tripped over it.",
            "",
            "| count | failure class | stage(s) | known issue | models |",
            "|---|---|---|---|---|",
        ]
        ordered = sorted(
            snap.signatures.values(), key=lambda s: (-s["count"], s["failure_class"])
        )
        for sig in ordered:
            models = ", ".join(sig["models"][:6]) + (
                f" +{len(sig['models']) - 6}" if len(sig["models"]) > 6 else ""
            )
            lines.append(
                f"| {sig['count']} | `{sig['failure_class'] or '?'}` | "
                f"{', '.join(sig['stages'])} | {sig['known_issue'] or '— **new**'} | {models} |"
            )
        lines.append("")

        unknown = [s for s in ordered if not s["known_issue"]]
        if unknown:
            lines += [
                f"**{len(unknown)} signature(s) have no known issue yet.** These are the",
                "discovery queue — each one is either a new constraint to document or a",
                "bug in the harness. `zoo report --new-signatures` lists them.",
                "",
            ]

    if snap.infra_events:
        lines += [
            "## Board reliability",
            "",
            f"{snap.infra_events} infra event(s) recorded — wedged probe, serial timeout,",
            "loader failure. These are counted here and **excluded from every verdict**:",
            "a broken bench is not a property of a model.",
            "",
        ]

    return "\n".join(lines)


DEFAULT_PATH = ROOT / "RESULTS.md"


def write(snap: Snapshot, path: Path | None = None, *, recipes: dict | None = None) -> Path:
    path = path or DEFAULT_PATH
    path.write_text(render(snap, recipes=recipes) + "\n")
    return path
